viaa:
    logging:
        level: DEBUG
app:
    pulsar:
        host: !ENV ${PULSAR_HOST}
        port: !ENV ${PULSAR_PORT}
        consumer_topic: !ENV ${TRANSFORMATOR_CONSUMER_TOPIC}
        producer_topic: !ENV ${TRANSFORMATOR_PRODUCER_TOPIC}